# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-18 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Durasi_Keluhan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Keluhan',
        ),
    ]
