# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-19 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0003_auto_20200619_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='Hidung_Tersumbat',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
