# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-20 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0004_postmodel_hidung_tersumbat'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='Nafas_Berbunyi',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmodel',
            name='Nafas_Tersedu_Sedu',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmodel',
            name='Penurunan_Kesadaran',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
